- Rewrote option parsing to use the 'opts' module

diff --git a/source/proxy/install b/source/proxy/install
--- a/source/proxy/install
+++ b/source/proxy/install
@@ -29,6 +29,11 @@ if [ ! -d "./node_modules/jsdom" ]; then
     npm install 'jsdom@0.2.13' || { echo "Installation failed" >&2; exit 1; }
 fi
 
+if [ ! -d "./node_modules/opts" ]; then
+    echo "  * Installing opts"
+    npm install 'opts@1.2.2' || { echo "Installation failed" >&2; exit 1; }
+fi
+
 if [ ! -d "./node_modules/html5" ]; then
     echo "  * Installing html5"
     npm install 'html5@v0.3.5' || { echo "Installation failed" >&2; exit 1; }
