- Removed patch for jsdom (latest version seems to have fixed the bug) - Added readme

diff --git a/source/proxy/install b/source/proxy/install
--- a/source/proxy/install
+++ b/source/proxy/install
@@ -16,8 +16,8 @@ if [ ! -d "./node_modules/jsdom" ]; then
     echo "  * Installing jsdom"
     npm install jsdom || { echo "Installation failed" >&2; exit 1; }
 
-    echo "    Patching jsdom"
-    patch -p1 < patch/jsdom.patch || { echo "Patch failed" >&2; exit 1; }
+    #echo "    Patching jsdom"
+    #patch -p1 < patch/jsdom.patch || { echo "Patch failed" >&2; exit 1; }
     echo "    Patching htmlparser"
     patch -p1 < patch/htmlparser.patch || { echo "Patch failed" >&2; exit 1; }
 fi
